module.exports = {
    //...require('./dom_hs.fi'),
    name: null,
    author: null,
    url: null,
    last_url: null,
    regex: null,
    title_path: null,
    comic_path: null,
    next_path: null,
    list_path: null,
    extension: null,
    //image_src: null,
    //javascript: null,
    dom_navigation: null,
    is_daily: true,
    genre: null,
    disabled: false,
    
}